# ----
# Site

title: TNP Reporting Manual
url: "https://chicago.github.io"
baseurl: "/tnp-reporting-manual"
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /favicon.ico
description: Formatting and reporting instructions for Transportation Network Providers for the City of Chicago.
author:
  name: City of Chicago
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Edition Template
  links:
    - https://github.com/Chicago/tnp-reporting-manual

# -----
# Build

permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
