# Project information
site_name: TNP Reporting Manual
site_description: Reporting requirements for Transportation Network Partners
site_author: City of Chicago
site_url: https://chicago.github.io/tnp-reporting-manual/

# Repository
repo_name: Chicago/tnp-reporting-manual
repo_url: https://github.com/Chicago/tnp-reporting-manual
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2016-2017 <a href="http://www.cityofchicago.org">City of Chicago</a>

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: false
  palette:
    primary: blue
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo:
    icon: "directions_car"

extra:
  social:
    - type: envelope-o
      link: mailto:BACPPV@cityofchicago.org